version: "3"
services:
  api:
    container_name: streaming_api
    build:
      context: .
      dockerfile: Dockerfile
    image: streaming_api
    ports:
      - "8086:8086"
  frontend:
    container_name: streaming_frontend
    build:
      context: Streaming.Frontend/
      dockerfile: Dockerfile
    image: streaming_frontend
    ports:
      - "8080:3000"